### Save Person

POST http://localhost:3000/api/person
Content-Type: application/json

{
  "name": "Peter",
  "age": 45,
  "mail": "peter@schwarz.de",
  "height": 1.85
}

### Get Person

GET http://localhost:8080/api/person/Peter
Accept: application/json

<> 2022-10-18T163155.200.json

### Get Custom-Header

GET http://localhost:3000/api/header
Custom-Header: Hello World!